exclude: ".venv|build"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
      args: ["--maxkb=6000"]
    - id: end-of-file-fixer
  - repo: local
    hooks:
    - id: cpplint
      name: cpplint
      description: Run `cpplint` against C/C++ header and source files
      language: python
      files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
      entry: cpplint
